{application,founderia,
             [{registered,[]},
              {description,"founderia"},
              {vsn,"0.0.1"},
              {modules,['Elixir.Avatar','Elixir.Data.Store',
                        'Elixir.Founderia','Elixir.Perlin','Elixir.Room',
                        'Elixir.Util.Id','Elixir.Util.Log',
                        'Elixir.World.Builder','Elixir.World']},
              {applications,[kernel,stdlib,elixir]}]}.